spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/todolist
    username: todo5
    password: todo1234!
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update  # 실행 시 엔티티 기반으로 테이블 자동 생성 또는 수정
    show-sql: true      # 콘솔에 SQL 쿼리 보이게 하기
    properties:
      hibernate:
        format_sql: true  # SQL 예쁘게 출력

  jackson:
    time-zone: Asia/Seoul  # 시간 설정 (LocalDateTime 쓸 때)
