spring:
  application:
    name: todolist
  jackson:
    time-zone: Asia/Seoul
  profiles:
    active: docker  # 기본은 docker 프로파일을 사용 (도커에서 실행할 땐 이걸 씀)

---
spring:
  config:
    activate:
      on-profile: docker
  datasource:
    url: jdbc:mariadb://mariadb:3306/todolist
    username: todo5
    password: todo1234!
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

---
spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:mariadb://localhost:3306/todolist
    username: todo5
    password: todo1234!
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
